---
- hosts: all
  become: yes
  tasks:
  - name: Autoremove packages
    shell: |
      apt autoremove -y
  - name: Clear apt cache
    shell: apt-get clean
  - name: Create empty file
    shell: |
      dd if=/dev/zero of=/EMPTY
      rm /EMPTY -rf
    failed_when: false
  - name: Cleanup
    file:
      path: /EMPTY
      state: absent