---
- hosts: all
  become: yes
  tasks:
  - name: Upgrade
    apt:
      update_cache: yes
      upgrade: full
  - name: Install mate and lightdm
    apt:
      name: "{{ item }}"
      state: present
    notify:
      - Enable lightdm
      - Enable autologin
    loop:
      - mate-core
      - lightdm
  - name: Clear apt cache
    shell: apt-get clean
  - name: Create empty file
    shell: |
      dd if=/dev/zero of=/EMPTY
      rm /EMPTY -rf
    failed_when: false
  - name: Cleanup
    file:
      path: /EMPTY
      state: absent
  handlers:
  - name: Enable lightdm
    service:
      name: lightdm
      state: started
      enabled: yes
  - name: Enable autologin
    lineinfile:
      path: /etc/lightdm/lightdm.conf
      regexp: "^#autologin-user"
      line: autologin-user=vagrant
