---
name: Packer

on:
  push:
    branches:
    - main

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: posts/00003-vagrant-box-for-buster64

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: posts/00003-vagrant-box-for-buster64
        env:
          PACKER_LOG: 1

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            posts/00003-vagrant-box-for-buster64/packer_cache
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      # additional steps to process artifacts

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            posts/00003-vagrant-box-for-buster64/target/*
